remote_theme: pages-themes/midnight@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Dissecting clouds and atmospheres of the coldest substellar worlds with JWST
tagline: Cool Stars 23 splinter session
description: A splinter session organized by Emily Rickman at Cool Stars 23 in Tokyo, Japan.
